apiVersion: v1
kind: ConfigMap
metadata:
  name: envsense-receiver-config
  namespace: fluentbit-etl
data:
  fluent-bit.yaml: |
    service:
      flush: 5
      daemon: off
      log_level: info
      storage.path: /tmp/storage
      storage.sync: normal

    pipeline:
      inputs:
        - name: tcp
          listen: 0.0.0.0
          port: 25000
          format: json
          tag: sensor.data
          mem_buf_limit: 10MB
          chunk_size: 32
          buffer_size: 64

      outputs:
        - name: kafka
          match: sensor.data
          brokers: 192.168.30.24:9092,192.168.30.25:9092,192.168.30.26:9092,192.168.30.27:9092
          topics: envsensor-pr
          format: json
          rdkafka.request.required.acks: 1
          rdkafka.compression.codec: snappy
          rdkafka.queue.buffering.max.ms: 50