apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-nfs-pv
  labels:
    app: airflow-dags
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 192.168.30.9
    path: /mnt/datahub/airflow-dags
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-nfs-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: airflow-dags-nfs-pv