#################################################################################
# secrets.yaml
#  Secrets contained here should not end up in github
#################################################################################

# Rancher K3S related values
keepalived_vrrp_password: <change me>
k3s_cluster_token: <change me>

#For msm email forwarding in our playbooks
admin_user: <change me>
admin_email: <change me>
gmail_user_email: <change me>
gmail_app_pw: <change me>

# for Kafka playbooks
kafka_admin_user: <change me>
kafka_admin_pw: <change me>
kafka_rw_user: <change me>
kafka_rw_pw: <change me>
kafka_ro_user: <change me>
kafka_ro_pw: <change me>
kafka_cluster_id: <change me>