---
#################################################################################
# LBSetup.yaml
#  Ansible playbook to install and maintain load balancer services
#################################################################################
- name: Install and Configure HAProxy and Keepalived for K3s Control Plane
  hosts: lb
  become: yes
  gather_facts: yes

  vars_files:
    - "{{ lookup('env', 'MYDHUB') }}/secrets.yaml"

  vars:
    k3s_shared_ip: "192.168.30.100"
    k3s_api_port: 6443
    keepalived_interface: "{{ ansible_default_ipv4.interface }}"

  tasks:
    - name: Install haproxy and keepalived
      ansible.builtin.package:
        name:
          - haproxy
          - keepalived
          - net-tools  # Provides netstat for the improved health check
        state: present

    - name: Copy HAProxy health check script
      ansible.builtin.template:
        src: templates/check_haproxy.sh.j2
        dest: /usr/local/bin/check_haproxy.sh
        mode: '0755'

    - name: Configure HAProxy
      ansible.builtin.template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: Restart haproxy

    - name: Configure Keepalived
      ansible.builtin.template:
        src: templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        mode: '0644'
      notify: Restart keepalived

    - name: Allow HAProxy to bind to any IP
      ansible.posix.sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: '1'
        state: present
        reload: yes

    - name: Ensure services are started and enabled
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - haproxy
        - keepalived

  handlers:
    - name: Restart haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted

    - name: Restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted