---
######################################################
- name: Install Kafka on target nodes
  hosts: kafka
  become: true
  vars:
    kvers: 4.1.0 # Kafka version
    svers: 2.13  # Scala version for Kafka
    kurl: "https://downloads.apache.org/kafka/{{kvers}}/kafka_{{svers}}-{{kvers}}.tgz"
    kafka_cluster_id: "" # Will be generated
  vars_files: [secrets.yaml]
  tasks:
  #################################################################
  # Create a zookeeper user and the necessary folders
    - name: Create Kafka user
      ansible.builtin.user:
        name: kafka
        shell: /bin/bash
        password: "!"
     
    - name: create kafka folders
      file:
        path: '{{item}}'
        state: directory
        owner: kafka
        group: kafka
        recurse: yes
        mode: 0755
      loop: [/var/kafka, /var/logs/kafka]

  #################################################################
  # Download and install kafka
    - name: Download Kafka
      get_url:
        url: "{{kurl}}"
        dest: /tmp/kafka.tar.gz
        force: yes

    - name: Extract tar to opt folder
      shell: |
        tar -xvf /tmp/kafka.tar.gz -C /tmp/
        mv /tmp/kafka_{{svers}}-{{kvers}} /opt/kafka

    - name: Set ownership of opt kafka folder
      file:
        path: /opt/kafka
        owner: kafka
        group: kafka
        recurse: true

    - name: Install Java JDK
      apt:
        pkg: default-jdk
        state: present

    - name: Format Kafka storage
      ansible.builtin.command: "/opt/kafka/bin/kafka-storage.sh format -t {{ kafka_cluster_id }} -c /opt/kafka/config/server.properties"
      args:
        creates: /var/kafka/meta.properties
      become_user: kafka

    - name: Create Kafka config file
      ansible.builtin.template:
        src: templates/kafka.server.properties.j2
        dest: /opt/kafka/config/server.properties
        owner: kafka
        group: kafka
        mode: "0644"

    - name: Create Kafka admin properties for ACL script
      ansible.builtin.template:
        src: templates/admin.properties.j2
        dest: /opt/kafka/config/admin.properties
        owner: kafka
        group: kafka
        mode: "0644"
  
    - name: Create Kafka JAAS config file
      ansible.builtin.template:
        src: templates/kafka_server_jaas.conf.j2
        dest: /opt/kafka/config/kafka_server_jaas.conf
        owner: kafka
        group: kafka
        mode: "0644"

  #################################################################
  # Create the kafka service
    - name: Create Kafka systemd service file
      ansible.builtin.template:
        src: templates/kafka.service.j2
        dest: "/etc/systemd/system/kafka.service"
        owner: root
        group: root
        mode: '0644'
      notify: Restart Kafka
    
    - name: Enable the Kafka service
      systemd:
        name: kafka
        enabled: yes
        state: started

  #################################################################
  # Configure Kafka ACLs
    - name: Set ACL for read-write user
      ansible.builtin.command: >
        /opt/kafka/bin/kafka-acls.sh
        --bootstrap-server localhost:9092
        --command-config /opt/kafka/config/admin.properties
        --add
        --allow-principal User:{{ kafka_rw_user }}
        --operation Read --operation Write --operation Create
        --topic '*'
        --group '*'
      run_once: true
      become_user: kafka

    - name: Set ACL for read-only user
      ansible.builtin.command: >
        /opt/kafka/bin/kafka-acls.sh
        --bootstrap-server localhost:9092
        --command-config /opt/kafka/config/admin.properties
        --add
        --allow-principal User:{{ kafka_ro_user }}
        --operation Read
        --topic '*'
        --group '*'
      run_once: true
      become_user: kafka

  handlers:
    - name: Restart Kafka
      ansible.builtin.service:
        name: kafka
        state: restarted